//CREACION DE UN COMPONENTE//

//CREAMOS UNA CONSOLO SOBRE LA CARPETA COMPONENTS

//EJECUTAMOS EL SIGUIENTE CODIGO 
//EN ESTE EJEMPLO SE CREARA EL COMPONENTE pagePresentation
//ng g m pagePresentation --module app --route pagePresentation

